/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./components/common/AlertMessage.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppNumberInput: typeof import('./components/common/AppNumberInput.vue')['default']
    AppTabs: typeof import('./components/common/AppTabs.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    Button: typeof import('./components/common/Button.vue')['default']
    Card: typeof import('./components/common/Card.vue')['default']
    Dot: typeof import('./components/common/Dot.vue')['default']
    Dropdown: typeof import('./components/common/Dropdown.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExpandCollapseBtn: typeof import('./components/common/ExpandCollapseBtn.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    InfoCell: typeof import('./components/common/InfoCell.vue')['default']
    InfoCellToggle: typeof import('./components/common/InfoCellToggle.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    Logo: typeof import('./components/common/Logo.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    Route: typeof import('./components/common/Route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/common/SearchInput.vue')['default']
    Sidebar: typeof import('./components/common/Sidebar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
